model:
  num_cells: 256
  lr: 3e-4
  actor_lr: 1e-4
  critic_lr: 3e-4
  max_grad_norm: 1.0

  bc_pretrained_model: "models/bc_pretrained.pt" # path to BC actor (pretrain_bc.py)
  vae_checkpoint_path: "loss=0.1050.ckpt" #* IMPORTANT: Path to pretrained encoder to load for VAE training

  gamma: 0.99
  tau: 0.05

  alpha: 0.2
  alpha_lr: 3e-4
  alpha_min: 0.1

  batch_size: 128
  replay_size: 1_000_000

  update_every: 8
  updates_per_step: 2
  actor_update_delay: 2

  freeze_encoder_steps: 50000

  load_initial: true

  per_alpha: 0.6
  per_beta: 0.4

  #* noisy - IGNORE IF use_noisy=false
  use_noisy: false
  noise_sigma: 0.5

  #* exploration - IGNORE IF use_noisy=true
  explore_start: 1
  explore_end: 0.03
  explore_steps: 500_000
